config/routes.rb
Rails.application.routes.draw do


  root "posts#index"

  resources :students
  

  get 'js_test', to: 'pages#js_test'

  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'new', to: 'pages#new'

  resources :tags
  
  resources :posts do 
  	resources :comments
  end 




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
end
 

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	validates :title, presence: true

	has_many :post_taggings
  	has_many :tags, through: :post_taggings
	
end

app/models/post_tagging.rb
class PostTagging < ApplicationRecord
	 belongs_to :post
  	 belongs_to :tag
end

app/models/student.rb
class Student < ApplicationRecord
	validates :name, presence: true
	validates :email, presence: true
	validates :email, uniqueness: true

	def days_to_birthday 
		birthdate_this_year = Date.new(Time.zone.today.year, birthdate.month, birthdate.day)
		days = birthdate_this_year - Time.zone.today 

		if days < 0 
		#birthday has past 
			birthdate_next_year = Date.new(Time.zone.today.year + 1, birthdate.month, birthdate.day)
			birthdate_next_year - Time.zone.today 
		else 
			days 
		end

	end

end

app/models/tag.rb
class Tag < ApplicationRecord
	 has_many :post_taggings
  	 has_many :posts, through: :post_taggings

  	 validates :name, presence: true
  	 validates :name, uniqueness: true
end

app/models/view_counter.rb
class ViewCounter < ApplicationRecord




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		post = Post.find(params[:post_id])
		@comment = Comment.new(comment_params)
		post.comments.create(comment_params)

		redirect_to post_path(id: post.id) 
	end

	def show
	end

	def new
	end

	def index
	end
	
	


	def comment_params 
		params.require(:comment).permit(:author, :body, :post_id)
	end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  

def home  
    flash[:notice] = 'THIS IS A NOTICE ON THE HOMEPAGE'
  end

  def about
    flash[:notice] = 'THIS IS A NOTICE ON THE ABOUT PAGE'
  end


  def new 
  end

  def js_test
    @posts = Post.all

  end

end

# def home
  #   h = ViewCounter.find_by(page_name: 'home')
  #   h.view_count += 1
  #   h.save

  # end

  # def about
  #   a = ViewCounter.find_by(page_name: 'about')
  #   a.view_count += 1
  #   a.save
  # end

  # def new
  #   n = ViewCounter.find_by(page_name: 'new')
  #   n.view_count += 1
  #   n.save
  # end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 def new
    @post = Post.new

  end

  def create
    @post = Post.new(post_params)
    if @post.save
        flash[:notice] = 'Post was successfully created.'
        redirect_to post_path(id: @post.id)
        

      else
         flash.now[:notice] = "Post is not created."
        render 'new'
      end
  
  end

  def show
      @post = Post.find(params[:id])
      @comment = @post.comments.new
      @tag = @post.tags.new

      
  end

  def index
      @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash.now[:notice] = "Post has been successfully updated."
      redirect_to @post

    else
      flash[:notice] = "Post is not successfully updated."
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Post has been successfully destroyed."
    redirect_to posts_path
    
  end
   
   private
    def post_params
      params.require(:post).permit(:title, :author, :text)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

 before_action :find_student, only: [:show, :edit, :update, :destroy]
 
  def new
	 @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
        flash[:notice] = 'Student record was successfully created.'
        redirect_to student_path(id: @student.id)
    else
         flash.now[:notice] = "Student record is not created."
        render 'new'
    end
  end


  def show
  end

  def index
      @students = Student.all
  end

  def edit
  end

  def update
    if @student.update(student_params)
      flash.now[:notice] = "Student record has been successfully updated."
      redirect_to student_path(id: @student.id)
    else
      flash[:notice] = "Student record is not successfully updated."
      render 'edit'
    end
  end

  def destroy
    @student.destroy
    flash[:notice] = "Student record has been successfully destroyed."
    redirect_to students_path
  end
   
   private
    def student_params
      params.require(:student).permit(:name, :birthdate, :email)
    end

    def find_student
    	@student = Student.find(params[:id])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def create
		post = Post.find(params[:post_id])
		@tag = Tag.new(tag_params)
		post.tags.create(tag_params)

		redirect_to post_path(id: post.id) 
	end

	def show
	end

	def new
	end

	def index
	end
	
	


	def tag_params 
		params.require(:tag).permit(:name, :post_id)
	end
end

app/controllers/user_application_controller.rb
class UserApplicationController < ApplicationController

  before_action :authenticate_user!
  
end

app/controllers/view_counters_controller.rb
class ViewCountersController < ApplicationController

  # GET /posts/new




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/view_counters_helper.rb
module ViewCountersHelper
end

app/views/posts/edit.html.erb
<h1>Edit post</h1>
 


<%= form_for @post, url: post_path do |f| %>

 <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>


<% end %>

<br>
<br>
<%= link_to posts_path, class: 'btn btn-warning' do %>
 <i class="glyphicon glyphicon-home"></i> Back 
<% end %>

app/views/posts/index.html.erb
<h1>List of all Posts</h1>
 
<table class="table table-hover">
  
  <thead>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Text</th>
    <th>Tag</th>
    <th>Time-created</th>
  </tr>
  </thead>


 <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.author %></td>
      <td><%= post.text %></td>
      <td><% post.tags.each do |tag| %>
       <%= tag.name %>
        <% end %>    
      </td>
      <td><%= post.created_at.strftime("%d-%b-%Y, %l:%M%P") %></td>

      <td><%= link_to 'Show', post_path(post), class: 'btn btn-success btn-xs' %></td>


      <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-info btn-xs' %></td>


      <td><%= link_to 'Destroy', post_path(post),
      class: 'btn btn-danger btn-xs',
              method: :delete,
              data: { confirm: 'Sure you wanna destroy?'} %> </td>
    </tr>
  <% end %>
  </tbody>

</table>

<br>
<%= link_to new_post_path, class: 'btn btn-warning' do %>
 <i class="glyphicon glyphicon-plus"></i> New Post
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for :post, url: posts_path do |f| %>


  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<br>
<br>



<%= link_to 'Back', posts_path, class: 'btn btn-warning' %>

app/views/posts/show.html.erb
<h1>Show Page</h1>

<p>
  <strong>Tag:</strong>
  <% @post.tags.each do |tag| %>
    <%= tag.name %>
  <% end %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<p>
  <strong>Time:</strong>
  <%= @post.created_at %>
</p>

<br>
<br>


<%= link_to 'Back', posts_path, class: 'btn btn-warning' %>

<hr>

<h3>Comment:</h3>

<%= form_for @comment, url: post_comments_path(post_id: @post.id), method: :post do |f| %> 

<%= f.hidden_field :post_id %> 
<p><strong>Name </strong><br> <%= f.text_field :author %></p> 
<p><strong>Comment</strong> <br> <%= f.text_area :body %></p>  

<p><%= f.submit "Comment" %></p>

<% end %>
<br>

  <h3>Comments</h3>

  <% @post.comments.each do |comment| %>
    
    <p><%= comment.author %><p> 
    <p><%= comment.body %></p> <br>
  <% end%>

app/views/students/edit.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1>Edit Student Record</h1>

	<%= form_for @student, url: student_path do |f| %>


	<% if @student.errors.any? %>
		<div id="errors"> 
			<h2> <%= pluralize(@student.errors.count, "error") %> prevented this Student record from saving </h2> 
			<ul> <% @student.errors.full_messages.each do |msg| %>
				<li> <%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>


	   <p>
	    <%= f.label :name %><br>
	    <%= f.text_field :name %>
	  </p>

	   <p>
	    <%= f.label :birthdate %><br>
	    <%= date_field(:student, :birthdate) %>
	  </p>

	  <p>
	    <%= f.label :email %><br>
	    <%= email_field(:student, :email) %>
	  </p>

	 
	  <p>
	    <%= f.submit %>
	  </p>
	<% end %>
	<br>
	<br>

	<%= link_to 'Back', students_path, class: 'btn btn-warning' %>

</div>

app/views/students/index.html.erb
<h1>List of all Student Records</h1>
 
<table class="table table-hover">
  
  <thead>
  <tr>
    <th>Name</th>
    <th>Birthdate</th>
    <th>Email</th>

    <th>Time Created</th>
  </tr>
  </thbook


 <tbody>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.birthdate %></td>
      <td><%= student.email %></td>

      <td><%= student.created_at.strftime("%d-%b-%Y, %l:%M%P") %></td>

      <td><%= link_to 'Show', student_path(student), class: 'btn btn-success btn-xs' %></td>


      <td><%= link_to 'Edit', edit_student_path(student), class: 'btn btn-info btn-xs' %></td>


      <td><%= link_to 'Destroy', student_path(student),
      class: 'btn btn-danger btn-xs',
              method: :delete,
              data: { confirm: 'Sure you wanna destroy?'} %> </td>
    </tr>
  <% end %>
  </tbody>

</table>

<br>
<%= link_to new_student_path, class: 'btn btn-warning' do %>
 <i class="glyphicon glyphicon-plus"></i> New Post
<% end %>

app/views/students/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>This is the new page to key in a student record</h1>

	<%= form_for @student, url: students_path do |f| %>


	<% if @student.errors.any? %>
		<div id="errors"> 
			<h2> <%= pluralize(@student.errors.count, "error") %> prevented this Student record from saving </h2> 
			<ul> <% @student.errors.full_messages.each do |msg| %>
				<li> <%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	  <p>
	    <%= f.label :name %><br>
	    <%= f.text_field :name %>
	  </p>

	   <p>
	    <%= f.label :birthdate %><br>
	    <%= date_field(:student, :birthdate) %>
	  </p>

	  <p>
	    <%= f.label :email %><br>
	    <%= email_field(:student, :email) %>
	  </p>



	  



	
	 
	  <p>
	    <%= f.submit %>
	  </p>
	<% end %>
	<br>
	<br>

	<%= link_to 'Back', students_path, class: 'btn btn-warning' %>
</div>

app/views/students/show.html.erb
<div class="col-md-10 col-md-offset-1">
	<div class="table-responsive">
	  <table class="table table table-hover">

		<h1><%= @student.name %></h1>

		    <thead>
		      <tr>
		      	<th>Name</th>
		        <th>Birthdate</th>
		        <th>Email</th>
		        <th>Created Date</th>
		      </tr>
		    </thead>

		    <tbody>
		      <tr>
		      	<td><%= @student.name %></td>
		        <td><%= @student.birthdate %></td>
		        <td><%= @student.email %></td>
		        <td><%= @student.created_at.strftime("%d %b %Y %A, %I:%S %p") %></td>
		      </tr>
		    </tbody>
		  
	  </table>
	</div>



	<div class="col-md-4 col-md-offset-4">
		<button type="button" class="btn btn-warning btn-lg">
			<%= link_to "Back", root_path %> 
		</button>
		<button type="button" class="btn btn-warning btn-lg">
			<%= link_to "Edit", edit_student_path(@student) %> 
		</button>
		<button type="button" class="btn btn-warning btn-lg">
			<%= link_to "Delete", student_path(@student), 
			method: :delete, 
			data: {confirm: "Sure you wanna destroy this record?"} %> 
		</button>


		<br>
	</div>
	
</div>